arb-dir: lib/language/l10n  #Specify the directory for arb files
template-arb-file: app_en.arb #Specify the template arb file
output-dir: lib/language/l10n/gen
output-class: AppLocalizations
output-localization-file: app_localizations.dart  #Specify the generated dart file name
untranslated-messages-file: lib/language/l10n/gen/app_localizations_untranslated.json
format: true
